name: main_workflow

on:
  push:
    branches: nodejs_nodeversions_job

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10, 12]


    steps:
      
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Setting node version
      - uses: actions/setup-node@v2

      - name: Linter execution
        uses: github/super-linter@v4
        env:
            DEFAULT_BRANCH: nodejs_example
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH: /
            JAVASCRIPT_ES_CONFIG_FILE: eslintrc.json
            VALIDATE_JAVASCRIPT_ES: true