name: main_workflow

on:
  
  push:
    branches: nodejs_nodeversions_job

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Linter execution
        uses: github/super-linter@v4.9.4
        env:
            DEFAULT_BRANCH: nodejs_example
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LINTER_RULES_PATH: /
            JAVASCRIPT_ES_CONFIG_FILE: eslintrc.json
            VALIDATE_JAVASCRIPT_ES: true