name: main_workflow

on:
  push:
    branches: nodejs_nodeversions_job

jobs:
  build:
    name: Linter execution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node: 10.10.0
          - node: 12.12.0

    steps:
      - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v3
      - name: Linter execution
        uses: github/super-linter@v4.9.4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  segundojob:
    name: test-execution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run jest test
        run: 
          npm install jest
          npm install
          npm test

  tecerjob:
    runs-on: ubuntu-latest
    name: Hola 2DAW
    steps:
    - name: Practica 6 step
      id: DESTINATION_PERSON
      uses: actions/github-actions-hello@v1.0
      with:
        who-to-greet: 'Hello 2DAW'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.DESTINATION_PERSON.outputs.time }}"

